<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class PlansSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        $plans = [
            [
                'code' => 'community',
                'name' => 'Community',
                'price_usd' => 0.00,
                'rfqs_per_month' => 3,
                'invoices_per_month' => 5,
                'users_max' => 3,
                'storage_gb' => 1,
                'erp_integrations_max' => 0,
                'analytics_enabled' => false,
                'analytics_history_months' => 3,
                'risk_scores_enabled' => false,
                'risk_history_months' => 0,
                'approvals_enabled' => false,
                'approval_levels_limit' => 0,
                'rma_enabled' => false,
                'rma_monthly_limit' => 0,
                'credit_notes_enabled' => false,
                'global_search_enabled' => false,
                'quotes_enabled' => false,
                'quote_revisions_enabled' => false,
                'digital_twin_enabled' => false,
                'maintenance_enabled' => false,
                'inventory_enabled' => false,
                'inventory_history_months' => 0,
                'pr_enabled' => false,
                'multi_currency_enabled' => false,
                'tax_engine_enabled' => false,
                'localization_enabled' => false,
                'exports_enabled' => false,
                'export_row_limit' => 0,
                'data_export_enabled' => false,
                'export_history_days' => 0,
            ],
            [
                'code' => 'starter',
                'name' => 'Starter',
                'price_usd' => 2400.00,
                'rfqs_per_month' => 10,
                'invoices_per_month' => 20,
                'users_max' => 5,
                'storage_gb' => 3,
                'erp_integrations_max' => 0,
                'analytics_enabled' => false,
                'analytics_history_months' => 12,
                'risk_scores_enabled' => false,
                'risk_history_months' => 6,
                'approvals_enabled' => false,
                'approval_levels_limit' => 0,
                'rma_enabled' => false,
                'rma_monthly_limit' => 0,
                'credit_notes_enabled' => false,
                'global_search_enabled' => false,
                'quotes_enabled' => false,
                'quote_revisions_enabled' => false,
                'digital_twin_enabled' => false,
                'maintenance_enabled' => false,
                'inventory_enabled' => false,
                'inventory_history_months' => 6,
                'pr_enabled' => false,
                'multi_currency_enabled' => false,
                'tax_engine_enabled' => false,
                'localization_enabled' => false,
                'exports_enabled' => false,
                'export_row_limit' => 0,
                'data_export_enabled' => false,
                'export_history_days' => 0,
            ],
            [
                'code' => 'growth',
                'name' => 'Growth',
                'price_usd' => 4800.00,
                'rfqs_per_month' => 100,
                'invoices_per_month' => 200,
                'users_max' => 25,
                'storage_gb' => 25,
                'erp_integrations_max' => 1,
                'analytics_enabled' => true,
                'analytics_history_months' => 24,
                'risk_scores_enabled' => true,
                'risk_history_months' => 24,
                'approvals_enabled' => true,
                'approval_levels_limit' => 3,
                'rma_enabled' => true,
                'rma_monthly_limit' => 20,
                'credit_notes_enabled' => true,
                'global_search_enabled' => true,
                'quotes_enabled' => true,
                'quote_revisions_enabled' => true,
                'digital_twin_enabled' => false,
                'maintenance_enabled' => false,
                'inventory_enabled' => true,
                'inventory_history_months' => 12,
                'pr_enabled' => true,
                'multi_currency_enabled' => true,
                'tax_engine_enabled' => true,
                'localization_enabled' => true,
                'exports_enabled' => true,
                'export_row_limit' => 50000,
                'data_export_enabled' => true,
                'export_history_days' => 30,
            ],
            [
                'code' => 'enterprise',
                'name' => 'Enterprise',
                'price_usd' => null,
                'rfqs_per_month' => 0,
                'invoices_per_month' => 0,
                'users_max' => 0,
                'storage_gb' => 0,
                'erp_integrations_max' => null,
                'analytics_enabled' => true,
                'analytics_history_months' => 36,
                'risk_scores_enabled' => true,
                'risk_history_months' => 36,
                'approvals_enabled' => true,
                'approval_levels_limit' => 5,
                'rma_enabled' => true,
                'rma_monthly_limit' => 0,
                'credit_notes_enabled' => true,
                'global_search_enabled' => true,
                'quotes_enabled' => true,
                'quote_revisions_enabled' => true,
                'digital_twin_enabled' => true,
                'maintenance_enabled' => true,
                'inventory_enabled' => true,
                'inventory_history_months' => 36,
                'pr_enabled' => true,
                'multi_currency_enabled' => true,
                'tax_engine_enabled' => true,
                'localization_enabled' => true,
                'exports_enabled' => true,
                'export_row_limit' => 0,
                'data_export_enabled' => true,
                'export_history_days' => 180,
            ],
        ];

        $payload = array_map(function (array $plan) use ($now) {
            return array_merge($plan, [
                'created_at' => $now,
                'updated_at' => $now,
            ]);
        }, $plans);

        DB::table('plans')->upsert(
            $payload,
            ['code'],
            ['name', 'price_usd', 'rfqs_per_month', 'invoices_per_month', 'users_max', 'storage_gb', 'erp_integrations_max', 'analytics_enabled', 'analytics_history_months', 'risk_scores_enabled', 'risk_history_months', 'approvals_enabled', 'approval_levels_limit', 'rma_enabled', 'rma_monthly_limit', 'credit_notes_enabled', 'global_search_enabled', 'quotes_enabled', 'quote_revisions_enabled', 'digital_twin_enabled', 'maintenance_enabled', 'inventory_enabled', 'inventory_history_months', 'pr_enabled', 'multi_currency_enabled', 'tax_engine_enabled', 'localization_enabled', 'exports_enabled', 'export_row_limit', 'data_export_enabled', 'export_history_days', 'updated_at']
        );
    }
}
