<?php

namespace Database\Factories;

use App\Models\Company;
use App\Models\Invoice;
use App\Models\InvoiceDisputeTask;
use App\Models\PurchaseOrder;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<InvoiceDisputeTask>
 */
class InvoiceDisputeTaskFactory extends Factory
{
    protected $model = InvoiceDisputeTask::class;

    public function definition(): array
    {
        $company = Company::factory();
        $purchaseOrder = PurchaseOrder::factory()->for($company);

        return [
            'company_id' => $company,
            'invoice_id' => Invoice::factory()->for($company)->for($purchaseOrder, 'purchaseOrder'),
            'purchase_order_id' => $purchaseOrder,
            'goods_receipt_note_id' => null,
            'resolution_type' => $this->faker->randomElement(['hold', 'request_credit_note', 'adjust_po']),
            'status' => 'open',
            'summary' => $this->faker->sentence(),
            'owner_role' => $this->faker->randomElement(['buyer_admin', 'finance_admin']),
            'requires_hold' => $this->faker->boolean(),
            'due_at' => now()->addDays($this->faker->numberBetween(1, 10)),
            'actions' => [[
                'type' => 'request_credit_note',
                'description' => 'Request supplier credit note for variance.',
                'owner_role' => 'buyer_admin',
                'due_in_days' => 5,
            ]],
            'impacted_lines' => [[
                'line_reference' => 'Line 1',
                'issue' => 'Qty variance',
                'severity' => 'warning',
                'variance' => 8,
                'recommended_action' => 'Hold payment until resolved.',
            ]],
            'next_steps' => ['Notify supplier of hold', 'Create NCR record'],
            'notes' => ['Generated by factory'],
            'reason_codes' => ['qty_warning'],
            'created_by' => User::factory()->for($company),
        ];
    }
}
