<?php

return [
    'disk' => env('DOCUMENTS_DISK', env('FILESYSTEM_DISK', 's3')),
    'max_size_mb' => env('DOCUMENTS_MAX_SIZE_MB', 50),
    'download_ttl_minutes' => (int) env('DOCUMENTS_DOWNLOAD_TTL', 10),
    'allowed_extensions' => [
        'step',
        'stp',
        'iges',
        'igs',
        'dwg',
        'dxf',
        'sldprt',
        'stl',
        '3mf',
        'pdf',
        'doc',
        'docx',
        'xls',
        'xlsx',
        'csv',
        'png',
        'jpg',
        'jpeg',
        'tif',
        'tiff',
    ],
    'allowed_visibilities' => ['private', 'company', 'public'],
    'default_visibility' => env('DOCUMENTS_DEFAULT_VISIBILITY', 'company'),
];
