<?php

return [
    'admin_permission_key' => 'admin.console',

    'permission_groups' => [
        [
            'id' => 'platform',
            'label' => 'Platform',
            'description' => 'Administrative capabilities for tenant configuration.',
            'permissions' => [
                [
                    'key' => 'admin.console',
                    'label' => 'Admin Console access',
                    'description' => 'Allows entry to the admin console and elevated settings.',
                    'level' => 'admin',
                    'domain' => 'platform',
                ],
                [
                    'key' => 'plans.manage',
                    'label' => 'Manage plans & limits',
                    'description' => 'Edit plan pricing, feature flags, and tenant assignments.',
                    'level' => 'admin',
                    'domain' => 'platform',
                ],
                [
                    'key' => 'roles.manage',
                    'label' => 'Manage role templates',
                    'description' => 'Adjust platform role templates and permissions.',
                    'level' => 'admin',
                    'domain' => 'platform',
                ],
                [
                    'key' => 'api_keys.manage',
                    'label' => 'Issue API keys',
                    'description' => 'Create, rotate, and revoke tenant API keys.',
                    'level' => 'admin',
                    'domain' => 'platform',
                ],
                [
                    'key' => 'webhooks.manage',
                    'label' => 'Manage webhooks',
                    'description' => 'Create and manage webhook subscriptions and delivery retries.',
                    'level' => 'admin',
                    'domain' => 'platform',
                ],
                [
                    'key' => 'rate_limits.manage',
                    'label' => 'Rate limits',
                    'description' => 'Edit rate limit policies for tenants and APIs.',
                    'level' => 'admin',
                    'domain' => 'platform',
                ],
                [
                    'key' => 'audit.read',
                    'label' => 'View audit log',
                    'description' => 'Inspect audit trails for platform activity.',
                    'level' => 'read',
                    'domain' => 'platform',
                ],
            ],
        ],
        [
            'id' => 'sourcing',
            'label' => 'Sourcing',
            'description' => 'RFQs, quotes, and awards.',
            'permissions' => [
                [
                    'key' => 'rfqs.read',
                    'label' => 'View RFQs',
                    'description' => 'Read RFQs, bids, and statuses.',
                    'level' => 'read',
                    'domain' => 'sourcing',
                ],
                [
                    'key' => 'rfqs.write',
                    'label' => 'Manage RFQs',
                    'description' => 'Create/edit RFQs, invite suppliers, award lines.',
                    'level' => 'write',
                    'domain' => 'sourcing',
                ],
                [
                    'key' => 'quotes.read',
                    'label' => 'View quotes',
                    'description' => 'Inspect supplier quote submissions and scoring summaries.',
                    'level' => 'read',
                    'domain' => 'sourcing',
                ],
                [
                    'key' => 'quotes.write',
                    'label' => 'Manage quotes',
                    'description' => 'Review, shortlist, and award supplier quotes.',
                    'level' => 'write',
                    'domain' => 'sourcing',
                ],
                [
                    'key' => 'rfps.read',
                    'label' => 'View RFPs',
                    'description' => 'Read RFP briefs, evaluation criteria, and supplier proposals.',
                    'level' => 'read',
                    'domain' => 'sourcing',
                ],
                [
                    'key' => 'rfps.write',
                    'label' => 'Manage RFPs',
                    'description' => 'Create/edit project/service RFPs and publish them to suppliers.',
                    'level' => 'write',
                    'domain' => 'sourcing',
                ],
            ],
        ],
        [
            'id' => 'suppliers',
            'label' => 'Suppliers',
            'description' => 'Directory management and onboarding.',
            'permissions' => [
                [
                    'key' => 'suppliers.read',
                    'label' => 'View suppliers',
                    'description' => 'List suppliers, performance, and documents.',
                    'level' => 'read',
                    'domain' => 'suppliers',
                ],
                [
                    'key' => 'suppliers.write',
                    'label' => 'Manage suppliers',
                    'description' => 'Approve, suspend, or edit supplier profiles.',
                    'level' => 'write',
                    'domain' => 'suppliers',
                ],
                [
                    'key' => 'suppliers.apply',
                    'label' => 'Submit supplier applications',
                    'description' => 'Allow company owners to submit supplier enrollment requests.',
                    'level' => 'write',
                    'domain' => 'suppliers',
                ],
            ],
        ],
        [
            'id' => 'orders',
            'label' => 'Orders & Fulfillment',
            'description' => 'Purchase orders, receiving, and returns.',
            'permissions' => [
                [
                    'key' => 'orders.read',
                    'label' => 'View orders',
                    'description' => 'Read-only access to purchase orders and deliveries.',
                    'level' => 'read',
                    'domain' => 'orders',
                ],
                [
                    'key' => 'orders.write',
                    'label' => 'Manage orders',
                    'description' => 'Issue, edit, and cancel purchase orders.',
                    'level' => 'write',
                    'domain' => 'orders',
                ],
                [
                    'key' => 'receiving.write',
                    'label' => 'Manage receiving & QC',
                    'description' => 'Resolve receiving discrepancies and complete quality inspections.',
                    'level' => 'write',
                    'domain' => 'orders',
                ],
            ],
        ],
        [
            'id' => 'inventory',
            'label' => 'Inventory',
            'description' => 'Inventory, warehouses, and maintenance.',
            'permissions' => [
                [
                    'key' => 'inventory.read',
                    'label' => 'View inventory',
                    'description' => 'Read inventory balances and transactions.',
                    'level' => 'read',
                    'domain' => 'inventory',
                ],
                [
                    'key' => 'inventory.write',
                    'label' => 'Manage inventory',
                    'description' => 'Adjust stock and configure warehouses.',
                    'level' => 'write',
                    'domain' => 'inventory',
                ],
            ],
        ],
        [
            'id' => 'billing',
            'label' => 'Billing & Finance',
            'description' => 'Invoices, payments, and analytics.',
            'permissions' => [
                [
                    'key' => 'billing.read',
                    'label' => 'View billing data',
                    'description' => 'Access invoices, credit notes, and payment history.',
                    'level' => 'read',
                    'domain' => 'billing',
                ],
                [
                    'key' => 'billing.write',
                    'label' => 'Manage billing',
                    'description' => 'Issue credits, edit invoices, manage tax rules.',
                    'level' => 'write',
                    'domain' => 'billing',
                ],
                [
                    'key' => 'finance.write',
                    'label' => 'Manage finance workflows',
                    'description' => 'Approve invoices and run payment processing steps.',
                    'level' => 'write',
                    'domain' => 'billing',
                ],
            ],
        ],
        [
            'id' => 'analytics',
            'label' => 'Analytics & Insights',
            'description' => 'Dashboards, KPI history, and Copilot analytics queries.',
            'permissions' => [
                [
                    'key' => 'analytics.read',
                    'label' => 'View analytics',
                    'description' => 'Access analytics dashboards, KPIs, and AI summaries.',
                    'level' => 'read',
                    'domain' => 'analytics',
                ],
                [
                    'key' => 'analytics.generate',
                    'label' => 'Generate analytics',
                    'description' => 'Trigger analytics recalculations and Copilot multi-metric queries.',
                    'level' => 'write',
                    'domain' => 'analytics',
                ],
                [
                    'key' => 'view_forecast_report',
                    'label' => 'View forecast reports',
                    'description' => 'Access demand forecast accuracy reports and AI recommendations.',
                    'level' => 'read',
                    'domain' => 'analytics',
                ],
                [
                    'key' => 'view_supplier_performance',
                    'label' => 'View supplier performance reports',
                    'description' => 'Inspect supplier KPI scorecards and corrective actions.',
                    'level' => 'read',
                    'domain' => 'analytics',
                ],
                [
                    'key' => 'summarize_reports',
                    'label' => 'Summarize analytics reports',
                    'description' => 'Trigger Copilot-powered analytics summaries.',
                    'level' => 'write',
                    'domain' => 'analytics',
                ],
                [
                    'key' => 'forecasts.read',
                    'label' => 'Run forecasts',
                    'description' => 'Request Copilot demand and performance forecasts.',
                    'level' => 'write',
                    'domain' => 'analytics',
                ],
            ],
        ],
        [
            'id' => 'workspace',
            'label' => 'Workspace Utilities',
            'description' => 'Notifications, events, exports, and global search.',
            'permissions' => [
                [
                    'key' => 'notifications.read',
                    'label' => 'View notifications',
                    'description' => 'Receive in-app notifications and inbox updates.',
                    'level' => 'read',
                    'domain' => 'workspace',
                ],
                [
                    'key' => 'notifications.manage',
                    'label' => 'Manage notifications',
                    'description' => 'Configure notification preferences and resend events.',
                    'level' => 'write',
                    'domain' => 'workspace',
                ],
                [
                    'key' => 'events.manage',
                    'label' => 'Manage events',
                    'description' => 'Replay or retry outbound event deliveries/webhooks.',
                    'level' => 'write',
                    'domain' => 'workspace',
                ],
                [
                    'key' => 'ai.workflows.run',
                    'label' => 'Run AI workflows',
                    'description' => 'Start AI workflows and fetch pending Copilot steps.',
                    'level' => 'write',
                    'domain' => 'workspace',
                ],
                [
                    'key' => 'ai.workflows.approve',
                    'label' => 'Approve AI workflows',
                    'description' => 'Approve or reject AI workflow outputs before publishing changes.',
                    'level' => 'write',
                    'domain' => 'workspace',
                ],
                [
                    'key' => 'ai.admin',
                    'label' => 'Administer AI usage',
                    'description' => 'Access AI usage dashboards and manage Copilot governance.',
                    'level' => 'admin',
                    'domain' => 'workspace',
                ],
                [
                    'key' => 'exports.run',
                    'label' => 'Run exports',
                    'description' => 'Generate CSV/PDF exports and download archives.',
                    'level' => 'write',
                    'domain' => 'workspace',
                ],
                [
                    'key' => 'search.use',
                    'label' => 'Use global search',
                    'description' => 'Access global search results across modules.',
                    'level' => 'read',
                    'domain' => 'workspace',
                ],
                [
                    'key' => 'help.read',
                    'label' => 'View workspace guides',
                    'description' => 'Open Copilot step-by-step workspace guidance.',
                    'level' => 'read',
                    'domain' => 'workspace',
                ],
            ],
        ],
        [
            'id' => 'tenant_admin',
            'label' => 'Tenant Administration',
            'description' => 'Buyer-only workspace settings such as team roster, approvals, and units.',
            'permissions' => [
                [
                    'key' => 'tenant.settings.manage',
                    'label' => 'Manage tenant settings',
                    'description' => 'Invite or remove members, edit approvals, configure units of measure.',
                    'level' => 'write',
                    'domain' => 'tenant_admin',
                ],
            ],
        ],
    ],
];
