<?php

use App\Models\AiActionDraft;
use App\Models\Company;
use App\Models\GoodsReceiptNote;
use App\Models\Invoice;
use App\Models\InvoiceDisputeTask;
use App\Models\PurchaseOrder;
use App\Models\User;
use App\Services\Ai\Converters\AiDraftConversionService;
use Illuminate\Support\Carbon;
use Illuminate\Validation\ValidationException;

it('converts approved dispute drafts into tasks linked to invoice references', function (): void {
    Carbon::setTestNow('2025-03-12 09:00:00');

    $company = Company::factory()->create();
    $purchaseOrder = PurchaseOrder::factory()->for($company)->create();
    $invoice = Invoice::factory()->for($company)->for($purchaseOrder)->create([
        'invoice_number' => 'INV-7788',
    ]);
    $receipt = GoodsReceiptNote::factory()
        ->for($company)
        ->for($purchaseOrder)
        ->create([
            'number' => 'RCPT-77',
        ]);
    $user = User::factory()->for($company)->create();

    $payload = [
        'dispute_reference' => [
            'invoice' => [
                'id' => (string) $invoice->id,
                'number' => $invoice->invoice_number,
            ],
            'purchase_order' => [
                'id' => (string) $purchaseOrder->id,
                'number' => $purchaseOrder->po_number,
            ],
            'receipt' => [
                'id' => (string) $receipt->id,
                'number' => $receipt->number,
            ],
        ],
        'issue_summary' => 'Invoice lines exceed received quantity by 12 units.',
        'issue_category' => 'quantity_variance',
        'owner_role' => 'buyer_admin',
        'requires_hold' => true,
        'due_in_days' => 4,
        'actions' => [[
            'type' => 'request_credit',
            'description' => 'Request credit memo for variance.',
            'owner_role' => 'buyer_admin',
            'due_in_days' => 4,
            'requires_hold' => true,
        ]],
        'impacted_lines' => [[
            'reference' => 'PO Line 10',
            'issue' => '12 unit variance',
            'severity' => 'risk',
            'variance' => 12,
            'recommended_action' => 'Request NCR from supplier.',
        ]],
        'next_steps' => ['Send NCR to supplier', 'Update variance tracker'],
        'notes' => ['Generated by deterministic dispute tool'],
        'reason_codes' => ['qty_variance', 'risk_flag'],
    ];

    $draft = AiActionDraft::factory()->approved()->create([
        'company_id' => $company->id,
        'user_id' => $user->id,
        'approved_by' => $user->id,
        'approved_at' => now(),
        'action_type' => AiActionDraft::TYPE_INVOICE_DISPUTE_DRAFT,
        'input_json' => [
            'entity_context' => [
                'entity_type' => 'invoice',
                'entity_id' => $invoice->id,
            ],
            'inputs' => [],
        ],
        'output_json' => [
            'action_type' => AiActionDraft::TYPE_INVOICE_DISPUTE_DRAFT,
            'payload' => $payload,
        ],
    ]);

    app(AiDraftConversionService::class)->convert($draft->fresh(), $user);

    /** @var InvoiceDisputeTask|null $task */
    $task = InvoiceDisputeTask::query()->where('invoice_id', $invoice->id)->first();

    expect($task)->not->toBeNull();
    expect($task?->summary)->toContain('exceed received quantity');
    expect($task?->resolution_type)->toBe('quantity_variance');
    expect($task?->purchase_order_id)->toBe($purchaseOrder->id);
    expect($task?->goods_receipt_note_id)->toBe($receipt->id);
    expect($task?->owner_role)->toBe('buyer_admin');
    expect($task?->requires_hold)->toBeTrue();
    expect($task?->due_at?->toDateTimeString())->toBe(Carbon::now()->addDays(4)->toDateTimeString());
    expect($task?->actions)->toHaveCount(1);
    expect(data_get($task?->actions, '0.type'))->toBe('request_credit');
    expect(data_get($task?->impacted_lines, '0.reference'))->toBe('PO Line 10');
    expect($task?->next_steps)->toContain('Send NCR to supplier');
    expect($task?->reason_codes)->toContain('qty_variance');
});

it('requires an invoice reference when converting dispute drafts', function (): void {
    $company = Company::factory()->create();
    $user = User::factory()->for($company)->create();

    $payload = [
        'dispute_reference' => [
            'invoice' => [
                'id' => null,
                'number' => null,
            ],
        ],
        'issue_summary' => 'Missing invoice reference.',
        'issue_category' => 'data_error',
    ];

    $draft = AiActionDraft::factory()->approved()->create([
        'company_id' => $company->id,
        'user_id' => $user->id,
        'approved_by' => $user->id,
        'approved_at' => now(),
        'action_type' => AiActionDraft::TYPE_INVOICE_DISPUTE_DRAFT,
        'input_json' => [
            'entity_context' => [
                'entity_type' => 'invoice',
                'entity_id' => null,
            ],
            'inputs' => [],
        ],
        'output_json' => [
            'action_type' => AiActionDraft::TYPE_INVOICE_DISPUTE_DRAFT,
            'payload' => $payload,
        ],
    ]);

    expect(fn () => app(AiDraftConversionService::class)->convert($draft->fresh(), $user))
        ->toThrow(ValidationException::class);
});
