<?php

use App\Enums\InvoiceStatus;
use App\Models\AiActionDraft;
use App\Models\Company;
use App\Models\Invoice;
use App\Models\InvoiceDisputeTask;
use App\Models\PurchaseOrder;
use App\Models\User;
use App\Services\Ai\Converters\AiDraftConversionService;
use Illuminate\Support\Carbon;

test('it applies hold resolution and creates a dispute task', function (): void {
    Carbon::setTestNow('2025-03-09 12:00:00');

    $company = Company::factory()->create();
    $purchaseOrder = PurchaseOrder::factory()->for($company)->create();
    $invoice = Invoice::factory()
        ->for($company)
        ->for($purchaseOrder)
        ->create([
            'status' => InvoiceStatus::Submitted->value,
            'matched_status' => 'pending',
            'invoice_number' => 'INV-1001',
        ]);
    $user = User::factory()->for($company)->create(['role' => 'finance_admin']);

    $payload = [
        'invoice_id' => (string) $invoice->id,
        'resolution' => [
            'type' => 'hold',
            'summary' => 'Hold invoice until supplier issues credit note for qty variance.',
            'reason_codes' => ['qty_warning'],
            'confidence' => 0.82,
        ],
        'actions' => [[
            'type' => 'request_credit_note',
            'description' => 'Request supplier to issue credit note for 10 unit overbill.',
            'owner_role' => 'buyer_admin',
            'due_in_days' => 3,
            'requires_hold' => true,
        ]],
        'impacted_lines' => [[
            'line_reference' => 'Line 1',
            'issue' => 'Qty variance of 10 units',
            'severity' => 'warning',
            'variance' => 10,
            'recommended_action' => 'Hold invoice and request credit note.',
        ]],
        'next_steps' => ['Notify supplier of variance', 'Capture NCR reference'],
        'notes' => ['Generated by Copilot deterministic tool'],
    ];

    $draft = AiActionDraft::factory()->approved()->create([
        'company_id' => $company->id,
        'user_id' => $user->id,
        'approved_by' => $user->id,
        'approved_at' => now(),
        'action_type' => AiActionDraft::TYPE_INVOICE_MISMATCH_RESOLUTION,
        'input_json' => [
            'entity_context' => [
                'entity_type' => 'invoice',
                'entity_id' => $invoice->id,
            ],
            'inputs' => [],
        ],
        'output_json' => [
            'action_type' => AiActionDraft::TYPE_INVOICE_MISMATCH_RESOLUTION,
            'payload' => $payload,
        ],
    ]);

    /** @var AiDraftConversionService $conversion */
    $conversion = app(AiDraftConversionService::class);
    $conversion->convert($draft->fresh(), $user);

    $invoice->refresh();

    expect($invoice->matched_status)->toBe('hold');
    expect($invoice->status)->toBe(InvoiceStatus::BuyerReview->value);
    expect($invoice->review_note)->toContain('Hold invoice until supplier issues credit note');

    $task = InvoiceDisputeTask::query()->where('invoice_id', $invoice->id)->first();
    expect($task)->not->toBeNull();
    expect($task?->owner_role)->toBe('buyer_admin');
    expect($task?->requires_hold)->toBeTrue();
    expect($task?->due_at?->toDateTimeString())->toBe(Carbon::now()->addDays(3)->toDateTimeString());
    expect($task?->actions)->toHaveCount(1);
    expect($task?->next_steps)->toContain('Notify supplier of variance');
    expect($task?->reason_codes)->toContain('qty_warning');
});

test('it records partial approvals without forcing holds', function (): void {
    Carbon::setTestNow('2025-03-09 08:00:00');

    $company = Company::factory()->create();
    $purchaseOrder = PurchaseOrder::factory()->for($company)->create();
    $invoice = Invoice::factory()
        ->for($company)
        ->for($purchaseOrder)
        ->create([
            'status' => InvoiceStatus::BuyerReview->value,
            'matched_status' => 'pending',
            'invoice_number' => 'INV-2002',
        ]);
    $user = User::factory()->for($company)->create(['role' => 'finance_admin']);

    $payload = [
        'invoice_id' => (string) $invoice->id,
        'resolution' => [
            'type' => 'partial_approve',
            'summary' => 'Approve received quantity and hold remaining variance on PO.',
            'reason_codes' => ['partial_release'],
            'confidence' => 0.64,
        ],
        'actions' => [[
            'type' => 'adjust_po',
            'description' => 'Adjust PO line to reflect accepted quantity.',
            'due_in_days' => 2,
            'requires_hold' => false,
        ]],
        'impacted_lines' => [[
            'line_reference' => 'Line 2',
            'issue' => 'Pending receipt for 5 units',
            'severity' => 'info',
            'variance' => 5,
            'recommended_action' => 'Adjust PO and request updated schedule.',
        ]],
        'next_steps' => ['Notify supplier of approved qty'],
        'notes' => [],
    ];

    $draft = AiActionDraft::factory()->approved()->create([
        'company_id' => $company->id,
        'user_id' => $user->id,
        'approved_by' => $user->id,
        'approved_at' => now(),
        'action_type' => AiActionDraft::TYPE_INVOICE_MISMATCH_RESOLUTION,
        'input_json' => [
            'entity_context' => [
                'entity_type' => 'invoice',
                'entity_id' => $invoice->id,
            ],
            'inputs' => [],
        ],
        'output_json' => [
            'action_type' => AiActionDraft::TYPE_INVOICE_MISMATCH_RESOLUTION,
            'payload' => $payload,
        ],
    ]);

    app(AiDraftConversionService::class)->convert($draft->fresh(), $user);
    $invoice->refresh();

    expect($invoice->matched_status)->toBe('matched');
    expect($invoice->status)->toBe(InvoiceStatus::BuyerReview->value);

    $task = InvoiceDisputeTask::query()->where('invoice_id', $invoice->id)->latest('id')->first();
    expect($task)->not->toBeNull();
    expect($task?->owner_role)->toBe('finance_admin');
    expect($task?->requires_hold)->toBeFalse();
    expect(data_get($task?->actions, '0.type'))->toBe('adjust_po');
    expect(data_get($task?->actions, '0.description'))->toContain('Adjust PO');
});
